# Universidad Autonoma de Aguascalientes
## Departamento: Ciencias de la Computación
## Carrera: Ingenieria en Computación Inteligente
### Curso: Aprendizaje Inteligente (Machine Learning)
### Maestro: Dr. Francisco Javier Luna Rosas
### Alumno: Diego Alberto Aranda Gonzalez
### Semestre: Enero_Junio del 2024

#### Practica 5: Redes Neuronales

#### Librerias

In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
#from pandas import DataFrame

C:\Users\diego\AppData\Local\Temp\ipykernel_10476\3831314044.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


#### Cargamos los datos de la flor de iris

In [2]:
df = pd.read_csv("C:/Users/diego/Desktop/Universidad/6to-Semestre/Aprendizaje_Inteligente/iris.csv", delimiter=";",decimal=".")

print(df.shape)
print(df.head())

(150, 5)
   s.largo  s.ancho  p.largo  p.ancho    tipo
0      5.1      3.5      1.4      0.2  setosa
1      4.9      3.0      1.4      0.2  setosa
2      4.7      3.2      1.3      0.2  setosa
3      4.6      3.1      1.5      0.2  setosa
4      5.0      3.6      1.4      0.2  setosa


##### Elimina la variable categorica, deja las variables predictorias en X

In [3]:
X = df.iloc[:,0:4]
print(X.head())

   s.largo  s.ancho  p.largo  p.ancho
0      5.1      3.5      1.4      0.2
1      4.9      3.0      1.4      0.2
2      4.7      3.2      1.3      0.2
3      4.6      3.1      1.5      0.2
4      5.0      3.6      1.4      0.2


##### Elimina la variable categorica, deja las variables predictorias en Y

In [4]:
Y = df.iloc[:,4:5]
print(Y.head())

     tipo
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa


#### Se separan los datos con el 70% de los datos para entrenamiento y el 30% para testing

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.7, random_state=0)

#### Mediante el constructor inicializa la instancia_red
##### Nota: por defecto usa 100 nodos en cada capa oculta, "solver" es el método de optimización

In [6]:
#instancia_red = MLPClassifier(solver='lbfgs',random_state=0)
instancia_red = MLPClassifier()
print(instancia_red)

MLPClassifier()


#### Entrena el modelo llamando al método fit

##### Nota: Observe que no hay variable que guarde el modelo como en R, esto se debe a que al ser Python Orientado a Objetos, el modelo queda en un atributo de la instancia "instancia_red"

In [7]:
print(Y_train.iloc[:,0].values)
print(X_train)
instancia_red.fit(X_train,Y_train.iloc[:,0].values)

['setosa' 'setosa' 'setosa' 'versicolor' 'versicolor' 'setosa' 'setosa'
 'versicolor' 'setosa' 'virginica' 'versicolor' 'virginica' 'versicolor'
 'setosa' 'virginica' 'setosa' 'virginica' 'setosa' 'setosa' 'virginica'
 'setosa' 'virginica' 'versicolor' 'versicolor' 'versicolor' 'virginica'
 'virginica' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'virginica'
 'virginica' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'setosa' 'setosa' 'setosa' 'virginica' 'versicolor' 'virginica' 'setosa']
     s.largo  s.ancho  p.largo  p.ancho
0        5.1      3.5      1.4      0.2
34       4.9      3.1      1.5      0.1
28       5.2      3.4      1.4      0.2
55       5.7      2.8      4.5      1.3
75       6.6      3.0      4.4      1.4
35       5.0      3.2      1.2      0.2
23       5.1      3.3      1.7      0.5
74       6.4      2.9      4.3      1.3
31       5.4      3.4      1.5      0.4
118      7.7      2.6      6.9      2.3
57       4.9      2.4      3.3      1.0
131    

C:\Users\diego\AppData\Roaming\Python\Python312\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

#### Imprime las predicciones en testing

In [8]:
print("Las predicciones en Testing son: {}".format(instancia_red.predict(X_test)))

Las predicciones en Testing son: ['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'versicolor' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'setosa' 'virginica' 'versicolor' 'setosa' 'setosa' 'virginica'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'setosa' 'virginica'
 'versicolor' 'setosa' 'virginica' 'virginica' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa' 'virginica'
 'setosa' 'setosa' 'versicolor' 'virginica' 'virginica' 'virginica'
 'virginica' 'versicolor' 'virginica' 'versicolor' 'versicolor'
 'virginica' 'versicolor' 'virginica' 'virginica' 'versicolor' 'virginica'
 'versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'virginica' 'setosa' 'setosa' 'virginica' 'versicolor'
 'setosa' 'setosa' 'versicolor' 'setosa' 'virginica' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'seto

##### Función para calcular los índices de calidad del modelo

In [9]:
def indices_general(MC,nombres = None):
  precision_global = np.sum(MC.diagonal()) / np.sum(MC)
  error_global = 1 - precision_global
  precision_categoria  = pd.DataFrame(MC.diagonal()/np.sum(MC,axis = 1)).T
  if nombres!=None:
    precision_categoria.columns = nombres
  return {"Matriz de Confusión":MC,
          "Precisión Global":precision_global,
          "Error Global":error_global,
          "Precisión por categoría":precision_categoria}

##### Índices de Calidad del Modelo

In [10]:
prediccion = instancia_red.predict(X_test)
MC = confusion_matrix(Y_test, prediccion)
indices = indices_general(MC,list(np.unique(Y)))
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))



Matriz de Confusión:
[[33  0  0]
 [ 0 33  1]
 [ 0  2 36]]

Precisión Global:
0.9714285714285714

Error Global:
0.02857142857142858

Precisión por categoría:
   setosa  versicolor  virginica
0     1.0    0.970588   0.947368


#### Conclusiones

##### Referencias